// LLM-based summaries for BridgeBase
// Auto-generated by setup_summaries.py

methods {
    // NONDET summaries

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     * AI Analysis: The _processMessage method contains an inline assembly block that uses both `mload` and `mstore` instructions to manipulate the message payload by removing the first byte.
     */


}
