// LLM-based summaries for CcipBridge
// Auto-generated by setup_summaries.py

methods {
    // NONDET summaries

    /*
     * Recipe: computes a price
     * AI Analysis: The method computes and returns the native fee (price) for sending a CCIP cross-chain message by calling the router's getFee function.
     */
    function CcipBridge._bridgeQuote(uint256 _dstChain, bytes memory _payload, bytes calldata _options) internal returns (uint256, uint256) => NONDET;


}
