// Auto-generated base summaries for CcipBridge
// Generated by setup_summaries.py

import "CcipBridge_summaries.spec";
import "./CombinatorialModule_base_summaries.spec";
import "./Solady/UUPSUpgradeable.spec";
import "./PositionManager_full_summaries.spec";
import "./CTFHelpers_summaries.spec";
import "./CcipBridge_ccipSend_summary.spec";
import "./CombinatorialPayout_summaries.spec";