// Summaries for Exchange
// Auto-generated by setup_summaries.py

methods {
    // NONDET summaries

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._computeCreate2Address(address deployer, bytes32 bytecodeHash, bytes32 salt) internal returns (address) => NONDET;
    
    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._getSafeWalletAddress(address signer) internal returns (address) => NONDET;

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._isValidEOASignature(bytes32 hash, address maker, bytes calldata sig) internal returns (bool) => NONDET;

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._isValidERC1271(address signer, bytes32 hash, bytes calldata sig) internal returns (bool) => NONDET;

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._proxySalt(address signer) internal returns (bytes32) => NONDET;

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._safeSalt(address signer) internal returns (bytes32) => NONDET;

    /*
     * Recipe: contains inline assembly blocks with `mload` or `mstore` instructions
     */
    function Exchange._validateOrder(bytes32 orderHash, Exchange.Order calldata order, uint256 fillAmount, uint256 fee) internal returns (uint256) => NONDET;

    /*
     * Recipe: contains more than 3 non-linear operations (multiplication, division, exponentiation, or modulo)
     */
    function Exchange._validateTakerBuyMaker(Exchange.Order calldata takerOrder, Exchange.Order calldata makerOrder) internal => NONDET;

    /*
     * Recipe: contains more than 3 non-linear operations (multiplication, division, exponentiation, or modulo)
     */
    function Exchange._validateTakerSellMaker(Exchange.Order calldata takerOrder, Exchange.Order calldata makerOrder) internal => NONDET;


}
